import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  const clickedForPdf = async () => {
    // Capture current window's URL:
    const currentUrl = window.location.href;
    // Pass URL to the API's endpoint 'pdfGenerate' and then download the streamed-response:
    const returnedContent = await fetch(`/api/pdfGenerate?target=${currentUrl}`)
      // Convert response body (readable stream) to 'blob':
      .then((response) => response.blob())
      // Generate url for this blob:
      .then((blob) => URL.createObjectURL(blob))
      // Generate hidden link, insert url, and click-download:
      .then((href) => {
        const link = document.createElement("a");
        document.body.appendChild(link);
        link.style = "display: none";
        link.href = href;
        link.download = `${currentUrl}.pdf`;
        link.click();
      });
    // const returnedContent = await fetch(`/api/pdfGenerate?${currentUrl}`).then(
    //   (response) => {
    //     console.log("response:", response);
    //     const blob = new Blob([response.body], { type: "application/pdf" });
    //     const link = document.createElement("a");
    //     link.href = window.URL.createObjectURL(blob);
    //     link.download = `${currentUrl}.pdf`;
    //     link.click();
    //   }
    // );
    // console.log("returnedContent:", returnedContent);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button className={styles.btn} onClick={clickedForPdf}>
          Generate PDF
        </button>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <img
          src="https://images.dog.ceo/breeds/cotondetulear/100_2013.jpg"
          width={225}
          height={300}
        />
        <img
          src="https://images.dog.ceo/breeds/hound-walker/n02089867_2815.jpg"
          width={225}
          height={300}
        />
        <img
          src="https://images.dog.ceo/breeds/pembroke/n02113023_1257.jpg"
          width={225}
          height={300}
        />
        <img
          src="https://images.dog.ceo/breeds/papillon/n02086910_336.jpg"
          width={225}
          height={300}
        />
        <img
          src="https://images.dog.ceo/breeds/spaniel-irish/n02102973_1142.jpg"
          width={225}
          height={300}
        />
        <img
          src="https://images.dog.ceo/breeds/setter-irish/n02100877_2824.jpg"
          width={225}
          height={300}
        />
        <img
          src="https://images.dog.ceo/breeds/african/n02116738_6044.jpg"
          width={225}
          height={300}
        />
        <img
          src="https://images.dog.ceo/breeds/setter-gordon/n02101006_3442.jpg"
          width={225}
          height={300}
        />
        <img
          src="https://images.dog.ceo/breeds/terrier-bedlington/n02093647_1495.jpg"
          width={225}
          height={300}
        />
        <img
          src="https://images.dog.ceo/breeds/eskimo/n02109961_5597.jpg"
          width={225}
          height={300}
        />
        <img
          src="https://images.dog.ceo/breeds/poodle-toy/n02113624_1293.jpg"
          width={225}
          height={300}
        />
        <img
          src="https://images.dog.ceo/breeds/pitbull/pitbull dog.jpg"
          width={225}
          height={300}
        />
        <img
          src="https://images.dog.ceo/breeds/retriever-golden/n02099601_3388.jpg"
          width={225}
          height={300}
        />
        <img
          src="https://images.dog.ceo/breeds/puggle/IMG_070809.jpg"
          width={225}
          height={300}
        />
        <img
          src="https://images.dog.ceo/breeds/bulldog-french/n02108915_1866.jpg"
          width={225}
          height={300}
        />
        <img
          src="https://images.dog.ceo/breeds/poodle-medium/PXL_20210220_100624962.jpg"
          width={225}
          height={300}
        />
        <img
          src="https://images.dog.ceo/breeds/airedale/n02096051_7118.jpg"
          width={225}
          height={300}
        />
        <img
          src="https://images.dog.ceo/breeds/eskimo/n02109961_7861.jpg"
          width={225}
          height={300}
        />
        <img
          src="https://images.dog.ceo/breeds/dachshund/dachshund-2033796_640.jpg"
          width={225}
          height={300}
        />
        <img
          src="https://images.dog.ceo/breeds/newfoundland/n02111277_2769.jpg"
          width={225}
          height={300}
        />
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
